name: CD - Docker Build and Scan

on:
  push:
    branches: [main]

jobs:
  Docker_Build_And_Push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: sanayay123/sample-python-app
      IMAGE_TAG: latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME:$IMAGE_TAG .

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

      - name: Scan Docker image and fail on HIGH or CRITICAL
        run: |
          trivy image --severity HIGH,CRITICAL --exit-code 1 --ignore-unfixed --no-progress $IMAGE_NAME:$IMAGE_TAG

      - name: Log in to Docker Hub
        if: success()  # Only runs if Trivy scan passed
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Docker image
        if: success()
        run: docker push $IMAGE_NAME:$IMAGE_TAG
